spring.application.name=portfolio-backend

# =========================
# DATABASE
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET:4a2s6f8g0h1j3k5l7m9n1b3v5c7x9z1a2s4d6f8g0h2j4k6l8m0n2b4v6c8x0z2}
jwt.accessExpiration=${JWT_ACCESS_EXPIRATION:86400000}
